// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Friends struct {
	Sender   *User `json:"sender" gorm:"foreignKey:SenderID ; references:Email ; constraint:OnUpdate:CASCADE , onDelete:CASCADE"`
	SenderID string `json:"senderId" gorm:"primaryKey"`
	Receiver *User `json:"receiver" gorm:"foreignKey:ReceiverID ; references:Email ; constraint:OnUpdate:CASCADE , onDelete:CASCADE"`
	ReceiverID string `json:"receiverId" gorm:"primaryKey"`
	Accepted bool  `json:"accepted"`
}
