// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	UserID  string `json:"userID"`
	Privacy string `json:"privacy"`
	Text    string `json:"text"`
}

type Post struct {
	ID           string     `json:"id"`
	UserID       string     `json:"userId"`
	User         *User      `json:"user" gorm:"foreignKey:UserID ; references:Email ; constraint:OnUpdate:CASCADE , onDelete:CASCADE"`
	Privacy      string     `json:"privacy"`
	Text         string     `json:"text"`
	LikeCount    int        `json:"likeCount" gorm:"-"`
	CommentCount int        `json:"commentCount" gorm:"-"`
	Comment      *[]Comment `json:"comment" gorm:"-"`
	Files        *[]Post    `json:"file" gorm:"-"`
	GroupID      string     `json:"groupID"`
}
